name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to SERVER
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22             # Pastikan port didefinisikan (default 22)
          timeout: 30s         # Tambah timeout (default biasanya cukup, tapi bisa dicoba)
          command_timeout: 30m # Timeout untuk script yang dijalankan
          debug: true
          script: |
            cd ~/app/stomatrade-backend
            git pull origin main
            docker stop stomatrade_backend || true
            docker rm stomatrade_backend || true
            docker build -t stomatrade_backend:latest .
            docker run -d \
              --name stomatrade_backend \
              -p 3000:3000 \
              --env-file .env \
              stomatrade_backend:latest
            docker image prune -f
